version: '3.9'

networks:
  youtg-network:
    driver: bridge


services:
  telegram-bot:
    build: ./bot
    env_file:
      - ./bot/.env
    restart: always
    networks:
      - youtg-network

  worker:
    build: ./worker
    volumes:
      - ./worker:/app
    restart: always
    networks:
      - youtg-network